import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../redux/ReduxProvider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Car Learner's",
  description: "Generated by create next app",
};

// token
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZ29vZ2xlX2lkIjoiMTA5NjY2MTA4MzYyMTI3MjQ1ODIwIiwibmFtZSI6IkRlZXAgTWFraGFzYW5hIiwiZW1haWwiOnsidmFsdWUiOiJkZWVwbWFraGFzYW5hMTAxM0BnbWFpbC5jb20iLCJ2ZXJpZmllZCI6dHJ1ZX0sInBob3RvIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS0lzMlY0ZnkzbndBcDVWUHVsOW5HSGtUUHVWcUxvVFFpQm02Yk5VdmlPPXM5Ni1jIiwic3RvcmVfaWQiOls0LDUsOCw5LDEyLDE0LDE2LDE3XSwiaWF0IjoxNzA1NjQzNzA3fQ.Bub9SZNcf1iP0LWNwXo-slJH11cK3gxUSzyXtuycro0

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#1fa3d8" showSpinner={false} />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
